/**
 * Prompts that ask for nothing worth modelling: acknowledgements, greetings,
 * and the one-word nudges an agentic loop hands back. Matched after punctuation
 * is stripped, so `Hi!` and `thanks.` land here too.
 */
export const DEFAULT_KEYWORDS = [
	"hi",
	"hi there",
	"hey",
	"hello",
	"hello there",
	"yo",
	"sup",
	"hiya",
	"howdy",
	"thanks",
	"thank you",
	"ty",
	"thx",
	"cheers",
	"nice",
	"great",
	"awesome",
	"perfect",
	"cool",
	"sweet",
	"lovely",
	"well done",
	"good job",
	"nice work",
	"ok",
	"okay",
	"k",
	"sure",
	"yes",
	"yeah",
	"yep",
	"y",
	"no",
	"nope",
	"nah",
	"n",
	"continue",
	"go",
	"go on",
	"go ahead",
	"proceed",
	"next",
	"carry on",
	"keep going",
	"resume",
	"done",
	"stop",
	"wait",
	"hold on",
	"hmm",
	"hm",
	"oh",
	"ah",
	"i see",
	"got it",
	"makes sense",
	"make sense",
	"sounds good",
	"looks good",
	"lgtm",
	"agreed",
	"right",
	"correct",
	"exactly",
	"indeed",
];

/**
 * Filler that rides along with an acknowledgement — `hey there`, `continue
 * please`, `thanks bro`. Only the all-words rule consults it, and it still
 * needs a real keyword in the prompt, so a filler-heavy *ask* survives.
 */
export const FILLER = new Set([
	"there",
	"then",
	"again",
	"please",
	"pls",
	"bro",
	"man",
	"dude",
	"guys",
	"all",
	"everyone",
]);
